name: Workflow-task
run-name: ${{github.actor}} is performing this actions
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello-world
        run: echo "Hello World!"
      - name: Task start displaying files present
        run: ls
      - name: Create a document
        run: touch task.txt
      - name: Edit the document
        run: vi task.txt
     
      
