name: Workflow-task
run-name: ${{Github.author}} is performing this actions
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello-world
        run: echo "Hello World!"

